### ISSUE TITLE
Cannot find obj.rhp

### ISSUE THREAD

**Issue by Siemenc** [EricM81/PluginShim#2]
I can find all other files with their respective path but I don't see a .rhp file in the obj folder. How do I get it there? Can I just copy it from the bin folder to the obj folder?
![image](https://user-images.githubusercontent.com/10272127/72667256-1db23380-3a1a-11ea-904f-3c86ba892034.png)
I tried just referring to a .rhp file in that folder even though it's not there but when I try to debug it doesn't work. I set the breakpoint in the correct place but when I run the shimcommand it does nothing.

**Comment by Siemenc** [comment]
Almost a year after but I've just tried this again and got it to work. I don't know what I was doing wrong last time but it surely had nothing to do with the naming of the path as I thought it did. This is amazing, thanks a lot!

**Comment by EricM81** [comment]
Glad you found it, sorry I missed the first post.
